=== MichaelRzheutski/University/src/main/resources/xml/lecturer.xsd
<?xml version="1.0" encoding="UTF-8" ?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="lecturer" type="lecturerType"/>

    <xs:complexType name="departmentType">
        <xs:all>
            <xs:element type="xs:string" name="departmentName"/>
            <xs:element type="xs:byte" name="course"/>
        </xs:all>
        <xs:attribute type="xs:byte" name="id"/>
    </xs:complexType>

    <xs:complexType name="subjectType">
        <xs:all>
            <xs:element type="xs:string" name="subjectName"/>
            <xs:element type="xs:string" name="grade"/>
        </xs:all>
        <xs:attribute type="xs:byte" name="id"/>
    </xs:complexType>

    <xs:complexType name="lecturerType">
        <xs:all>
            <xs:element type="xs:string" name="firstName"/>
            <xs:element type="xs:string" name="lastName"/>
            <xs:element type="departmentType" name="department"/>
            <xs:element type="subjectType" name="subject"/>
            <xs:element type="xs:string" name="lecturerContactId"/>
        </xs:all>
        <xs:attribute type="xs:byte" name="id"/>
    </xs:complexType>
</xs:schema>

=== MichaelRzheutski/University/src/main/resources/xml/lecturer.xml
<lecturer id="1" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
          xsi:noNamespaceSchemaLocation="lecturer.xsd">
    <firstName>Сергей</firstName>
    <lastName>Пчёлкин</lastName>
    <department id="1">
        <departmentName>Кафедра перевода</departmentName>
        <course>1</course>
    </department>
    <subject id="1">
        <subjectName>Природоведение</subjectName>
        <grade> </grade>
    </subject>
    <lecturerContactId> </lecturerContactId>
</lecturer>
