=== MichaelRzheutski/University/src/main/resources/xml/semester.xsd
<?xml version="1.0" encoding="UTF-8" ?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

    <xs:element name="semester" type="semesterType"/>
    <xs:complexType name="semesterType">
        <xs:all>
            <xs:element type="xs:string" name="semesterName" minOccurs="0"/>
            <xs:element type="xs:byte" name="subjectId" minOccurs="0"/>
            <xs:element type="semestersType" name="semesters" minOccurs="0"/>
        </xs:all>
        <xs:attribute type="xs:byte" name="id" use="optional"/>
    </xs:complexType>
    <xs:complexType name="semestersType">
        <xs:sequence>
            <xs:element type="semesterType" name="semester" minOccurs="0" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>
</xs:schema>

=== MichaelRzheutski/University/src/main/resources/xml/semester.xml
<semester id="1" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
          xsi:noNamespaceSchemaLocation="semester.xsd">
    <semesters>
        <semester id="1">
            <semesterName>1 семестр</semesterName>
            <subjectId>1</subjectId>
        </semester>
        <semester id="2">
            <semesterName>2 семестр</semesterName>
            <subjectId>2</subjectId>
        </semester>
    </semesters>
</semester>
